### PR TITLE
for django3.1

### PR DESCRIPTION
**Pull request by wakita181009**
- FieldDoesNotExist is removed from django.db.models.fields in django3.1.
- psql: could not connect to server error on “travis-ci” (https://stackoverflow.com/questions/49850020/psql-could-not-connect-to-server-error-on-travis-ci)
- Not to support python 3.2 and 3.3 because these versions haven't already hosted on GCP

### CODE REVIEW

**Comment by cramaker** [comment]
:1st_place_medal: Thanks for this! It'd be great to have the latest Django support

**Comment by a1tus** [comment]
Is this repo still maintained or our only choice to use a fork?

We use the same import fix as in this PR and it would be nice to merge it and make a release so that people could use pip.

**Comment by maxtepkeev** [comment]
@wakita181009 Fantastic job, many thanks for this, merging it as it is.

Just one question, what's wrong with pymysql usage for the latest Django in travis ?

**Comment by a1tus** [comment]
@maxtepkeev great! Are you going to release 0.5.7 with this?

**Comment by maxtepkeev** [comment]
@a1tus I will, just wanna check a few more things so it might take a few more days.

**Comment by a1tus** [comment]
@maxtepkeev that's nice, thanks.

**Comment by wakita181009** [comment]
> @wakita181009 Fantastic job, many thanks for this, merging it as it is.
> 
> Just one question, what's wrong with pymysql usage for the latest Django in travis ?

@maxtepkeev 
I met some errors to use Django>=3.0 and pymysql and also Django recommended to use mysqlclient as MySQL driver.
https://docs.djangoproject.com/en/3.1/ref/databases/#mysql-db-api-drivers

**Pull request merged**
