### PR TITLE
Add python 3.7 support

### PR DESCRIPTION
**Pull request by Joozty**
I added python 3.7 support. I am not sure about changes made in `.travis.yml` since I don't have much experiences with using Travis CI.

### CODE REVIEW

**Comment by silentsokolov** [comment]
Thanks for PR!

But default image travis [don't supports Python 3.7](https://docs.travis-ci.com/user/languages/python/#specifying-python-versions). Fix this?

**Comment by thedrow** [comment]
Seems like SQLObject fails to install.

**Comment by Andrew-Chen-Wang** [comment]
Try to use #71 configurations for those looking into this.

**Comment by maxtepkeev** [comment]
Closed in favour of #75. Thanks anyway!

**Pull request closed without merging**
